/**
 * Bio component that queries for data
 * with Gatsby's useStaticQuery component
 *
 * See: https://www.gatsbyjs.com/docs/use-static-query/
 */

import * as React from "react"
import { useStaticQuery, graphql } from "gatsby"
import { StaticImage } from "gatsby-plugin-image"

const Bio = () => {
  const data = useStaticQuery(graphql`
    query BioQuery {
      site {
        siteMetadata {
          author {
            name
            summary
          }
          social {
            github
            mastodonInstance
            mastodonUsername
          }
        }
      }
    }
  `)

  // Set these values by editing "siteMetadata" in gatsby-config.js
  const author = data.site.siteMetadata?.author
  const social = data.site.siteMetadata?.social

  return (
    <div className="bio">
      <StaticImage
        className="bio-avatar"
        layout="fixed"
        formats={["auto", "webp", "avif"]}
        src="../images/fake-profile-pic.jpg"
        width={50}
        height={50}
        quality={95}
        alt="Fake AI genreated profile photo portraying a young Asian male,
          generated by generated.photos,
          modified with FaceApp and 
          upsampled using https://replicate.com/jingyunliang/swinir"
      />
      {author?.name && (
        <p>
          Written by <strong>{author.name}</strong>{author?.summary || null}.
          {` `}
          Follow them on:{` `}
          <a href={`https://github.com/${social?.github || ``}`}>
            GitHub
          </a>
          {` | `}
          <a href={`https://${social?.mastodonInstance || `joinmastodon.org`}/@${social?.mastodonUsername || ``}`} rel="me">
            Mastodon
          </a>.
        </p>
      )}
    </div>
  )
}

export default Bio
